
// DELCARE FUNCTION WITH A SINGLE PERM ARRAY AS INPUT

  // ITERATE OVER ARRAY TO  GENERATE ARRAY OF LOCATION NUMBERS:  --  (SEPARATE FUNCTION?)
    
    // 
    
    
    
  // ITERATE OVER LOCATIONS ARRAY:
  
    // ITERATE OVER EACH SUBSEQUENT ELEMENT (!!!) *UP TO COL# ONLY (!!!) :
    
      // TEST FOR DIAGONAL ALIGNMENT
      
        // IF ALIGNMENT FOUND:
        
          // RETURN FALSE (DO NOTHING IF NO ALIGNMENT FOUND)
          
  
  
  // RETURN TRUE (SINCE NO ALIGNMENT WAS FOUND)
          
